name: Jason Zhang
title: Jason Zhang | Blog
description: Jekflix is a template for Jekyll inspired by Netflix and made by Jason Zhang.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
email: youremail@xyz.com
disqus_username: disqus_username
show_hero: true
